# Reconciliation Types (matches DB ENUM)
RECONCILIATION_TYPE_INVOICE = "Invoice"
RECONCILIATION_TYPE_DEPOSIT = "Deposit"
RECONCILIATION_TYPE_SPECIAL_ASSESSMENT = "SpecialAssessment"
RECONCILIATION_TYPE_BANK_FEE = "BankFee"
RECONCILIATION_TYPE_INTEREST = "Interest"
RECONCILIATION_TYPE_MANUAL = "Manual"

RECONCILIATION_TYPES = {
    RECONCILIATION_TYPE_INVOICE,
    RECONCILIATION_TYPE_DEPOSIT,
    RECONCILIATION_TYPE_SPECIAL_ASSESSMENT,
    RECONCILIATION_TYPE_BANK_FEE,
    RECONCILIATION_TYPE_INTEREST,
    RECONCILIATION_TYPE_MANUAL,
}

# Payment Timing (matches DB ENUM)
PAYMENT_TIMING_EARLY = "Early"
PAYMENT_TIMING_ON_TIME = "OnTime"
PAYMENT_TIMING_LATE = "Late"

PAYMENT_STATUSES = {
    PAYMENT_TIMING_EARLY,
    PAYMENT_TIMING_ON_TIME,
    PAYMENT_TIMING_LATE,
}

# Reconciliation Status (matches DB ENUM)
STATUS_MATCHED = "Matched"
STATUS_NEEDS_REVIEW = "NeedsReview"
STATUS_RESOLVED = "Resolved"
STATUS_UNRESOLVED = "Unresolved"

RECONCILIATION_STATUSES = {
    STATUS_MATCHED,
    STATUS_NEEDS_REVIEW,
    STATUS_RESOLVED,
    STATUS_UNRESOLVED,
}
